export const restaurants = [
  {
    id: 'cesar',
    name: 'Cesar',
    tagline: 'Restauration Saine & Rapide',
    description: 'Fast food rapide et sain. Burgers, sandwiches et plats variés à Ouagadougou.',
    logo: '/assets/cesar.jpeg',
    coverImage: '/assets/cesar.jpeg',
    rating: 4.3,
    deliveryTime: '20-35 min',
    deliveryFee: 400,
    minOrder: 1500,
    latitude: 12.3665,
    longitude: -1.4807,
    location: 'Patte d Oie, Ouagadougou',
    phone: '+226 07 20 78 31',
    cuisineType: 'Fast Food',
    promo: 'Livraison gratuite',
    categories: ['Burgers', 'Sandwiches', 'Plats', 'Salades', 'Desserts', 'Boissons'],
    menu: [
      {
        id: 'ca1',
        name: 'Cesar Burger',
        description: 'Double steak, fromage cheddar, bacon, sauce Cesar',
        price: 4000,
        category: 'Burgers',
        image: 'https://images.unsplash.com/photo-1553979459-d2229ba7433b?w=600',
        popular: true,
        available: true,
      },
      {
        id: 'ca2',
        name: 'Chicken Sandwich',
        description: 'Filet de poulet grillé, mayonnaise, laitue, tomate',
        price: 3000,
        category: 'Sandwiches',
        image: 'https://images.unsplash.com/photo-1521390188846-e2a3a97453a0?w=600',
        popular: false,
        available: true,
      },
      {
        id: 'ca3',
        name: 'Plat du Jour',
        description: 'Riz au gras + poulet braisé + légumes sautés',
        price: 3500,
        category: 'Plats',
        image: 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=600',
        popular: true,
        available: true,
      },
      {
        id: 'ca4',
        name: 'Salade Cesar',
        description: 'Laitue romaine, poulet grillé, croutons, parmesan, sauce Cesar',
        price: 4000,
        category: 'Salades',
        image: 'https://images.unsplash.com/photo-1546793665-c74683f339c1?w=600',
        popular: false,
        available: true,
      },
    ],
  },
  {
    id: 'belchicken',
    name: 'BelChiken',
    tagline: 'Finest Fried Chicken & More',
    description: 'Poulet frit de qualité supérieure. Ailes, tenders, nuggets et plus encore.',
    logo: '/assets/belchiken.jpeg',
    coverImage: '/assets/belchiken.jpeg',
    rating: 4.4,
    deliveryTime: '30-45 min',
    deliveryFee: 600,
    minOrder: 2500,
    latitude: 12.3339,
    longitude: -1.4545,
    location: 'Projet Zaca, Ouagadougou',
    phone: '+226 70 00 00 02',
    cuisineType: 'Poulet Frit',
    promo: null,
    categories: ['Poulet Frit', 'Burgers', 'Nuggets', 'Combos', 'Sides', 'Boissons'],
    menu: [
      {
        id: 'b1',
        name: '8 Wings',
        description: '8 ailes de poulet panées sauce au choix',
        price: 5000,
        category: 'Poulet Frit',
        image: 'https://images.unsplash.com/photo-1567620832903-9fc6debc209f?w=600',
        popular: true,
        available: true,
      },
      {
        id: 'b2',
        name: 'Bel Burger',
        description: 'Burger poulet Belchicken, sauce spéciale, fromage',
        price: 3800,
        category: 'Burgers',
        image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=600',
        popular: false,
        available: true,
      },
      {
        id: 'b3',
        name: 'Nuggets (10 pcs)',
        description: '10 nuggets de poulet + sauce dips',
        price: 3500,
        category: 'Nuggets',
        image: 'https://images.unsplash.com/photo-1619881590738-a111d176d936?w=600',
        popular: false,
        available: true,
      },
      {
        id: 'b4',
        name: 'Family Combo',
        description: '16 wings + 8 tenders + 2 frites XL + 2 boissons 1L',
        price: 18000,
        category: 'Combos',
        image: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=600',
        popular: true,
        available: true,
      },
    ],
  },
  {
    id: 'chitir',
    name: 'ChitirChiken',
    tagline: 'Fried Chicken & More',
    description: 'Le meilleur poulet pané de Ouagadougou. Burgers, wraps, tenders et buckets pour tous les goûts.',
    logo: '/assets/chitirchiken.jpeg',
    coverImage: '/assets/chitirchiken.jpeg',
    rating: 4.5,
    deliveryTime: '25-40 min',
    deliveryFee: 500,
    minOrder: 2000,
    latitude: 12.3783,
    longitude: -1.5151,
    location: 'Ouaga 2000, Ouagadougou',
    phone: '+226 70 00 00 01',
    cuisineType: 'Fast Food',
    promo: null,
    categories: ['Burgers', 'Wraps', 'Buckets', 'Menus', 'Accompagnements', 'Boissons'],
    menu: [
      {
        id: 'c1',
        name: 'Chitir Burger',
        description: 'Burger poulet pané, sauce secrète, laitue, tomate',
        price: 3500,
        category: 'Burgers',
        image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=600',
        popular: true,
        available: true,
      },
      {
        id: 'c2',
        name: 'Hot Chitir Burger',
        description: 'Burger poulet pané épicé, sauce piquante, oignons croustillants',
        price: 3800,
        category: 'Burgers',
        image: 'https://images.unsplash.com/photo-1553979459-d2229ba7433b?w=600',
        popular: false,
        available: true,
      },
      {
        id: 'c3',
        name: 'Tornado Wrap',
        description: 'Wrap poulet pané enroulé, sauce garlic, légumes frais',
        price: 3200,
        category: 'Wraps',
        image: 'https://images.unsplash.com/photo-1626700051175-6818013e1d4f?w=600',
        popular: true,
        available: true,
      },
      {
        id: 'c4',
        name: 'Wings Bucket (10 pcs)',
        description: '10 ailes de poulet panées + frites XL + boisson 1L',
        price: 8500,
        category: 'Buckets',
        image: 'https://images.unsplash.com/photo-1567620832903-9fc6debc209f?w=600',
        popular: true,
        available: true,
      },
    ],
  },
  {
    id: 'gusto',
    name: 'Gusto',
    tagline: 'Mediterranean & Asian Cuisine',
    description: 'Cuisine méditerranéenne et asiatique raffinée. Pâtes, sushis, plats grillés et spécialités.',
    logo: '/assets/gusto.jpeg',
    coverImage: '/assets/gusto.jpeg',
    rating: 4.6,
    deliveryTime: '35-50 min',
    deliveryFee: 700,
    minOrder: 3000,
    latitude: 12.3529,
    longitude: -1.5137,
    location: 'Zone du Bois, Ouagadougou',
    phone: '+226 70 00 00 03',
    cuisineType: 'Cuisine Internationale',
    promo: '-20% sur les sushis',
    categories: ['Pates', 'Sushis', 'Grillades', 'Plats Chauds', 'Entrees', 'Boissons'],
    menu: [
      {
        id: 'g1',
        name: 'Spaghetti Bolognese',
        description: 'Pâtes fraîches, sauce bolognaise maison, parmesan',
        price: 4500,
        category: 'Pates',
        image: 'https://images.unsplash.com/photo-1551183053-bf91a1d81141?w=600',
        popular: true,
        available: true,
      },
      {
        id: 'g2',
        name: 'Sushi Mix (12 pcs)',
        description: 'Assortiment de 12 sushis : saumon, thon, crevette',
        price: 8000,
        category: 'Sushis',
        image: 'https://images.unsplash.com/photo-1579871494447-9811cf80d66c?w=600',
        popular: true,
        available: true,
      },
      {
        id: 'g3',
        name: 'Filet de Boeuf Grillé',
        description: 'Filet de boeuf 250g, sauce au poivre, légumes grillés',
        price: 9000,
        category: 'Grillades',
        image: 'https://images.unsplash.com/photo-1600891964092-4316c288032e?w=600',
        popular: false,
        available: true,
      },
      {
        id: 'g4',
        name: 'Riz Cantonais',
        description: 'Riz sauté aux légumes, crevettes, poulet, oeuf',
        price: 5000,
        category: 'Plats Chauds',
        image: 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=600',
        popular: false,
        available: true,
      },
    ],
  },
];

export const getRestaurantById = (id) => {
  return restaurants.find((r) => r.id === id);
};
