import React, { createContext, useContext, useState, useCallback } from 'react';

const translations = {
  fr: {
    // Navigation
    home: 'Accueil',
    search: 'Rechercher',
    cart: 'Panier',
    orders: 'Commandes',
    profile: 'Profil',
    // General
    loading: 'Chargement...',
    error: 'Erreur',
    success: 'Succès',
    yes: 'Oui',
    no: 'Non',
    save: 'Enregistrer',
    cancel: 'Annuler',
    confirm: 'Confirmer',
    back: 'Retour',
    retry: 'Réessayer',
    close: 'Fermer',
    delete: 'Supprimer',
    edit: 'Modifier',
    add: 'Ajouter',
    // Home
    deliveryTo: 'Livraison à',
    searchPlaceholder: 'Rechercher un plat, un restaurant...',
    allRestaurants: 'Tous les restaurants',
    sendPackage: 'Envoyer un colis',
    noResults: 'Aucun restaurant ne correspond à votre recherche',
    resetFilters: 'Réinitialiser les filtres',
    login: 'Connexion',
    loginAria: 'Se connecter',
    homeAria: "Retour à l'accueil",
    profileAria: 'Profil',
    notificationsAria: 'Notifications',
    heroTagline: 'Le bon repas, au bon moment',
    heroDesc: 'Vos restaurants préférés, livrés chauds chez vous.',
    heroOrder: 'Commander',
    heroLocation: 'Livraison à · Zone du Bois',
    // Cart
    emptyCart: 'Votre panier est vide',
    addItems: 'Ajoutez des plats pour commencer',
    exploreRestaurants: 'Explorer les restaurants',
    myCart: 'Mon Panier',
    clearCart: 'Vider le panier',
    summary: 'Récapitulatif',
    subtotal: 'Sous-total',
    deliveryFee: 'Frais de livraison',
    serviceFee: 'Frais de service',
    estimatedTotal: 'Total estimé',
    calculatedNext: "Calculés à l'étape suivante",
    minimumOrder: 'Minimum de commande',
    placeOrder: 'Passer la commande',
    securePayment: 'Paiement sécurisé avec Orange Money, Moov Money & Wave',
    // Profile
    myProfile: 'Mon Profil',
    fullName: 'Nom complet',
    email: 'Email',
    phone: 'Téléphone',
    address: 'Adresse',
    notificationChannel: 'Canal de notification préféré',
    saving: 'Enregistrement…',
    saved: 'Enregistré',
    addresses: 'Adresses de livraison',
    paymentInfo: 'Informations de paiement',
    notifications: 'Notifications',
    settings: 'Paramètres',
    logout: 'Déconnexion',
    myOrders: 'Mes commandes',
    myReceipts: 'Mes reçus',
    favorites: 'Favoris',
    noOrders: 'Aucune commande pour le moment',
    noReceipts: 'Aucun reçu pour le moment',
    noFavorites: 'Aucun favori pour le moment',
    addFavoritesHint: 'Ajoutez des restaurants en cliquant sur le cœur',
    orderNow: 'Commander',
    articles: 'article(s)',
    // Payment
    mobileMoneyNumber: 'Numéro Mobile Money',
    operator: 'Opérateur',
    selectOperator: 'Sélectionner un opérateur',
    paymentInfoDesc: 'Configurez votre numéro Mobile Money pour les retraits et dépôts.',
    // VIP
    vipPass: 'FasoFree Pass VIP',
    activeMember: 'Membre actif',
    exclusiveAdvantage: 'Avantage exclusif',
    platformFeesFree: 'Frais de plateforme offerts',
    switchToVip: 'Passez au FasoFree Pass VIP',
    vipDesc: 'Pendant toute la durée de votre abonnement, les frais de service / plateforme de {fee} par commande sont entièrement offerts. La livraison reste calculée selon la distance (min. 800 FCFA).',
    feePerOrder: '100 FCFA offerts / commande',
    noCommitment: 'Sans engagement',
    fasoFreeWallet: 'Portefeuille FasoFree',
    refresh: 'Actualiser',
    myStatus: 'Mon statut',
    activeSub: 'Abonné {plan} actif',
    expiresOn: 'Expire le {date}',
    notSubscribed: "Vous n'êtes pas encore abonné au Pass VIP.",
    chooseOffer: 'Choisissez votre offre',
    loadingOffers: 'Chargement des offerts…',
    autoRenew: 'Renouvellement automatique',
    subscribeFor: "S'abonner pour {price} FCFA",
    subscribing: 'Abonnement…',
    alreadyVip: 'Vous profitez déjà du Pass VIP',
    vipActiveDesc: 'Vos commandes ne paient plus les 100 FCFA de frais de plateforme.',
    rechargeWallet: 'Recharger le portefeuille',
    amountFcfa: 'Montant (FCFA)',
    recharge: 'Recharger',
    recharging: 'Recharge…',
    // Loyalty
    myPoints: 'Mes points',
    pointsPerSpent: '1 point / 100 FCFA depenses',
    equivalentReduction: 'équivalents: {amount} FCFA de réduction',
    referFriend: 'Parrainer un ami',
    friendsRegistered: '{count} ami(s) inscrit(s)',
    referred: 'Parrainés',
    pendingPoints: 'Points en attente',
    referrerBonus: 'Parrain: +500 pts | Filleul: +200 pts au 1er achat',
    // Checkout
    checkout: 'Commander',
    delivery: 'Me faire livraison',
    pickup: 'Venir récupérer',
    dineIn: 'Manger sur place',
    fulfillmentQuestion: 'Comment souhaitez-vous votre commande ?',
    deliveryAddress: 'Adresse de livraison',
    fullAddress: 'Adresse complète',
    deliveryInstructions: 'Instructions de livraison',
    contactInfo: 'Informations de contact',
    paymentMethod: 'Mode de paiement',
    sending: 'Envoi en cours...',
    confirmOrder: 'Confirmer la commande',
    selectPosition: 'Sélectionnez votre position',
    toBeCalculated: 'À calculer',
    gpsHint: "Cliquez sur 'Utiliser ma position actuelle' pour calculer les frais.",
    tableNumber: 'Numéro de table (optionnel)',
    guests: 'Nombre de convives',
    specialRequest: 'Demande spéciale',
    landmark: 'Repère local (optionnel)',
    useCurrentPosition: 'Utiliser ma position actuelle',
    enterAnotherAddress: 'Entrer une autre adresse',
    pickupInfo: 'Récupérez votre commande au restaurant.',
    onSite: 'Sur place',
    // Orders
    myOrdersTitle: 'Mes Commandes',
    statusPending: 'En attente',
    statusPaid: 'Payée',
    statusPreparing: 'En préparation',
    statusReady: 'Prête',
    statusDriverEnRoute: 'Livreur en chemin',
    statusDelivered: 'Livrée',
    statusCompleted: 'Terminée',
    statusCancelled: 'Annulée',
    filterAll: 'Toutes',
    filterPending: 'En attente',
    filterPaid: 'Payées',
    filterDelivered: 'Livrées',
    filterCancelled: 'Annulées',
    loadingOrders: 'Chargement des commandes...',
    loadError: 'Impossible de charger vos commandes',
    noOrdersYet: 'Aucune commande pour le moment',
    orderNumber: 'Commande #',
    // Search
    searchPlaceholderFull: 'Rechercher un plat, un restaurant...',
    noResultsFor: 'Aucun résultat pour',
    tryAnother: 'Essayez un autre terme',
    searchHint: 'Recherchez un restaurant ou un plat',
    // Restaurant
    loadingRestaurant: 'Chargement du restaurant...',
    restaurantNotFound: 'Restaurant non trouvé',
    searchDish: 'Rechercher un plat...',
    allCategories: 'Tous',
    popular: 'Populaires',
    menu: 'Menu',
    noDishFound: 'Aucun plat trouvé',
    cartLabel: 'Panier',
    addToCart: 'Ajouter',
    added: 'Ajouté',
    chooseBranch: 'Choisir une agence',
    closed: 'Fermé',
    removeFavorite: 'Retirer des favoris',
    addFavorite: 'Ajouter aux favoris',
    branches: 'agences',
    // Order Tracking
    orderTracking: 'Suivi de commande',
    stepConfirmed: 'Commande confirmée',
    stepPreparing: 'En préparation',
    stepEnRoute: 'En route',
    stepDelivered: 'Livrée',
    orderNumber: 'Numéro de commande',
    estimatedTime: 'Temps estimé',
    arrival: 'arrivée vers',
    preparation: 'Préparation',
    travel: 'Trajet',
    driverPosition: 'Position du livreur',
    liveTracking: 'Suivi en direct',
    discussion: 'Discussion',
    channelArchived: 'Canal archivé',
    withDriver: 'Avec le livreur',
    withMerchant: 'Avec le marchand',
    noMessages: 'Aucun message pour le moment.',
    discussionEnded: 'Discussion terminée.',
    writeMessage: 'Écrire un message...',
    channelClosed: 'Canal fermé',
    confirmReception: 'Confirmer la réception (Code PIN)',
    reportProblem: 'Signaler un problème',
    disputeSuccess: 'Litige ouvert avec succès...',
    disputePending: 'Un litige est en cours...',
    history: 'Historique',
    pinCodeHint: 'Saisissez le Code PIN à 4 chiffres reçu',
    // Dispute
    disputeTitle: 'Signaler un problème',
    incompleteOrder: 'Commande incomplète',
    neverDelivered: 'Jamais livrée',
    lateDelivery: 'Retard important',
    badCondition: 'Mauvais état',
    other: 'Autre',
    disputeReason: 'Motif du litige',
    problemDescription: 'Description du problème',
    confirmPassword: 'Confirmez votre mot de passe',
    send: 'Envoyer',
    sending2: 'Envoi...',
    // Notifications
    notifOrder: 'Commande',
    notifDelivery: 'Livraison',
    notifPromo: 'Promo',
    notifAccount: 'Compte',
    notifSystem: 'Système',
    notificationsTitle: 'Notifications',
    markAllRead: 'Tout marquer comme lu',
    noNotifications: 'Aucune notification',
    // Verify
    verifyAccount: 'Vérifiez votre compte',
    codeSentTo: 'Un code à 6 chiffres a été envoyé à',
    verifiedSuccess: 'Compte vérifié !',
    redirecting: 'Redirection en cours...',
    verifying: 'Vérification...',
    verify: 'Vérifier',
    resendIn: 'Renvoyer le code dans...',
    resendCode: 'Renvoyer le code',
    backToRegister: "Retour à l'inscription",
    // Auth
    loginTitle: 'Connexion',
    loginSubtitle: 'Accédez à votre espace FasoFree',
    emailOrPhone: 'Email ou Téléphone',
    password: 'Mot de passe',
    loginButton: 'Se connecter',
    forgotPassword: 'Mot de passe oublié ?',
    noAccount: 'Pas encore de compte ?',
    createAccount: 'Créer un compte',
    loginError: 'Email ou mot de passe incorrect',
    sendLink: 'Envoyer le lien',
    backToLogin: 'Retour à la connexion',
    resetPassword: 'Réinitialiser',
    passwordReset: 'Mot de passe réinitialisé ! Redirection...',
    // Register
    registerTitle: 'Créer un compte',
    registerSubtitle: 'Rejoignez FasoFree',
    clientTab: 'Client',
    merchantTab: 'Marchand',
    driverTab: 'Livreur',
    yourBusiness: 'Votre commerce',
    yourDriverProfile: 'Votre profil de livreur',
    documents: 'Documents (piece jointe)',
    referralCode: 'Code de parrainage',
    createClientAccount: 'Créer mon compte client',
    sendMerchantApp: 'Envoyer ma candidature marchand',
    sendDriverApp: 'Envoyer ma candidature livreur',
    alreadyHaveAccount: 'Vous avez déjà un compte ?',
    appSent: 'Candidature envoyée !',
    backToHome: "Retour à l'accueil",
    // Receipt
    orderReceipt: 'Recu de commande',
    loadingReceipt: 'Chargement du reçu...',
    loadReceiptError: 'Impossible de charger les details de la commande.',
    orderConfirmed: 'Commande confirmée !',
    orderInProgress: 'Commande en cours...',
    paidSuccess: 'Votre commande a été payée avec succès',
    waitingConfirmation: 'Votre commande est en attente de confirmation',
    date: 'Date',
    status: 'Statut',
    orderedItems: 'Articles commandés',
    totalPaid: 'Total payé',
    download: 'Télécharger',
    trackOrder: 'Suivre ma commande',
    thankYou: 'Merci de votre confiance !',
    confirmationEmail: 'Un email de confirmation a été envoyé à votre adresse.',
    // Addresses
    addressesTitle: 'Adresses de livraison',
    noAddresses: 'Aucune adresse enregistrée',
    addAddress: 'Ajouter une adresse',
    defaultLabel: 'Par défaut',
    newAddress: 'Nouvelle adresse',
    editAddress: "Modifier l'adresse",
    home: 'Domicile',
    office: 'Bureau',
    parents: 'Chez mes parents',
    otherAddress: 'Autre',
    fullAddressLabel: 'Adresse complète',
    useGps: 'Utiliser ma position GPS',
    positionSaved: 'Position enregistrée',
    setDefault: 'Définir comme adresse par defaut',
    deleteAddress: 'Supprimer cette adresse ?',
    // Footer
    tagline: 'La ville à votre table.',
    footerDesc: 'Livraison de repas premium à Ouagadougou et dans tout le Burkina Faso.',
    links: 'Liens',
    privacyPolicy: 'Politique de confidentialité',
    terms: "Conditions d'utilisation",
    contact: 'Contact',
    allRightsReserved: 'Tous droits réservés.',
    // Ride
    rideTitle: 'FasoFree Ride',
    economy: 'Économique',
    comfort: 'Confort',
    premium: 'Premium',
    departure: 'Point de départ',
    destination: 'Destination',
    contactPhone: 'Téléphone',
    vehicleType: 'Type de véhicule',
    fareEstimate: 'Estimation du tarif',
    estimateFare: 'Estimer le tarif',
    estimating: 'Estimation...',
    confirmRide: 'Confirmer la course',
    confirming: 'Confirmation...',
    rideConfirmed: 'Course confirmée !',
    trackRide: 'Suivre ma course en direct',
    // P2P
    p2pTitle: 'Envoyer un colis',
    p2pDesc: 'Course à la demande - Point A vers Point B',
    pickupAddress: 'Adresse de ramassage',
    deliveryAddress2: 'Adresse de livraison',
    contactName: 'Nom du contact',
    recipientName: 'Nom du destinataire',
    contactPhone2: 'Téléphone du contact',
    recipientPhone: 'Téléphone du destinataire',
    packageDetails: 'Détails du colis',
    packageDesc: 'Description du colis',
    weight: 'Poids estimé (kg)',
    declaredValue: 'Valeur déclarée du colis (FCFA)',
    fragile: 'Colis fragile',
    fragilityFee: 'Surcoût fragilité',
    weightFee: 'Surcoût poids',
    previous: 'Précédent',
    continue: 'Continuer',
    confirmTrip: 'Confirmer la course',
    tripConfirmed: 'Course confirmée !',
    sendAnother: 'Envoyer un autre colis',
    // Loading
    artOfTable: "L'art de la table",
    // RestaurantCard
    branchesLabel: 'agences',
  },
  en: {
    home: 'Home',
    search: 'Search',
    cart: 'Cart',
    orders: 'Orders',
    profile: 'Profile',
    loading: 'Loading...',
    error: 'Error',
    success: 'Success',
    yes: 'Yes',
    no: 'No',
    save: 'Save',
    cancel: 'Cancel',
    confirm: 'Confirm',
    back: 'Back',
    retry: 'Retry',
    close: 'Close',
    delete: 'Delete',
    edit: 'Edit',
    add: 'Add',
    deliveryTo: 'Delivery to',
    searchPlaceholder: 'Search for a dish, a restaurant...',
    allRestaurants: 'All restaurants',
    sendPackage: 'Send a package',
    noResults: 'No restaurant matches your search',
    resetFilters: 'Reset filters',
    login: 'Login',
    loginAria: 'Log in',
    homeAria: 'Back to home',
    profileAria: 'Profile',
    notificationsAria: 'Notifications',
    heroTagline: 'The right meal, at the right time',
    heroDesc: 'Your favorite restaurants, delivered hot to your door.',
    heroOrder: 'Order',
    heroLocation: 'Delivery to · Bois District',
    emptyCart: 'Your cart is empty',
    addItems: 'Add items to get started',
    exploreRestaurants: 'Explore restaurants',
    myCart: 'My Cart',
    clearCart: 'Clear cart',
    summary: 'Summary',
    subtotal: 'Subtotal',
    deliveryFee: 'Delivery fee',
    serviceFee: 'Service fee',
    estimatedTotal: 'Estimated total',
    calculatedNext: 'Calculated at the next step',
    minimumOrder: 'Minimum order',
    placeOrder: 'Place order',
    securePayment: 'Secure payment with Orange Money, Moov Money & Wave',
    myProfile: 'My Profile',
    fullName: 'Full name',
    email: 'Email',
    phone: 'Phone',
    address: 'Address',
    notificationChannel: 'Preferred notification channel',
    saving: 'Saving...',
    saved: 'Saved',
    addresses: 'Delivery addresses',
    paymentInfo: 'Payment information',
    notifications: 'Notifications',
    settings: 'Settings',
    logout: 'Log out',
    myOrders: 'My orders',
    myReceipts: 'My receipts',
    favorites: 'Favorites',
    noOrders: 'No orders yet',
    noReceipts: 'No receipts yet',
    noFavorites: 'No favorites yet',
    addFavoritesHint: 'Add restaurants by clicking the heart',
    orderNow: 'Order',
    articles: 'item(s)',
    mobileMoneyNumber: 'Mobile Money number',
    operator: 'Operator',
    selectOperator: 'Select an operator',
    paymentInfoDesc: 'Set up your Mobile Money number for withdrawals and deposits.',
    vipPass: 'FasoFree VIP Pass',
    activeMember: 'Active member',
    exclusiveAdvantage: 'Exclusive advantage',
    platformFeesFree: 'Platform fees free',
    switchToVip: 'Upgrade to FasoFree VIP Pass',
    vipDesc: 'During your subscription, platform/service fees of {fee} per order are fully covered. Delivery is calculated by distance (min. 800 FCFA).',
    feePerOrder: '100 FCFA free per order',
    noCommitment: 'No commitment',
    fasoFreeWallet: 'FasoFree Wallet',
    refresh: 'Refresh',
    myStatus: 'My status',
    activeSub: 'Subscriber {plan} active',
    expiresOn: 'Expires on {date}',
    notSubscribed: "You're not subscribed to the VIP Pass yet.",
    chooseOffer: 'Choose your offer',
    loadingOffers: 'Loading offers...',
    autoRenew: 'Auto-renewal',
    subscribeFor: 'Subscribe for {price} FCFA',
    subscribing: 'Subscribing...',
    alreadyVip: 'You already enjoy the VIP Pass',
    vipActiveDesc: 'Your orders no longer pay the 100 FCFA platform fee.',
    rechargeWallet: 'Top up wallet',
    amountFcfa: 'Amount (FCFA)',
    recharge: 'Top up',
    recharging: 'Topping up...',
    myPoints: 'My points',
    pointsPerSpent: '1 point / 100 FCFA spent',
    equivalentReduction: 'equivalent: {amount} FCFA discount',
    referFriend: 'Refer a friend',
    friendsRegistered: '{count} friend(s) registered',
    referred: 'Referred',
    pendingPoints: 'Pending points',
    referrerBonus: 'Referrer: +500 pts | Referred: +200 pts on 1st order',
    checkout: 'Order',
    delivery: 'Delivery',
    pickup: 'Pickup',
    dineIn: 'Dine in',
    fulfillmentQuestion: 'How would you like your order?',
    deliveryAddress: 'Delivery address',
    fullAddress: 'Full address',
    deliveryInstructions: 'Delivery instructions',
    contactInfo: 'Contact information',
    paymentMethod: 'Payment method',
    sending: 'Sending...',
    confirmOrder: 'Confirm order',
    selectPosition: 'Select your position',
    toBeCalculated: 'To be calculated',
    gpsHint: "Click 'Use my current position' to calculate fees.",
    tableNumber: 'Table number (optional)',
    guests: 'Number of guests',
    specialRequest: 'Special request',
    landmark: 'Local landmark (optional)',
    useCurrentPosition: 'Use my current position',
    enterAnotherAddress: 'Enter another address',
    pickupInfo: 'Pick up your order at the restaurant.',
    onSite: 'On site',
    myOrdersTitle: 'My Orders',
    statusPending: 'Pending',
    statusPaid: 'Paid',
    statusPreparing: 'Preparing',
    statusReady: 'Ready',
    statusDriverEnRoute: 'Driver en route',
    statusDelivered: 'Delivered',
    statusCompleted: 'Completed',
    statusCancelled: 'Cancelled',
    filterAll: 'All',
    filterPending: 'Pending',
    filterPaid: 'Paid',
    filterDelivered: 'Delivered',
    filterCancelled: 'Cancelled',
    loadingOrders: 'Loading orders...',
    loadError: 'Unable to load your orders',
    noOrdersYet: 'No orders yet',
    orderNumber: 'Order #',
    searchPlaceholderFull: 'Search for a dish, a restaurant...',
    noResultsFor: 'No results for',
    tryAnother: 'Try another term',
    searchHint: 'Search for a restaurant or a dish',
    loadingRestaurant: 'Loading restaurant...',
    restaurantNotFound: 'Restaurant not found',
    searchDish: 'Search for a dish...',
    allCategories: 'All',
    popular: 'Popular',
    menu: 'Menu',
    noDishFound: 'No dish found',
    cartLabel: 'Cart',
    addToCart: 'Add',
    added: 'Added',
    chooseBranch: 'Choose a branch',
    closed: 'Closed',
    removeFavorite: 'Remove from favorites',
    addFavorite: 'Add to favorites',
    branchesLabel: 'branches',
    orderTracking: 'Order tracking',
    stepConfirmed: 'Order confirmed',
    stepPreparing: 'Preparing',
    stepEnRoute: 'On the way',
    stepDelivered: 'Delivered',
    estimatedTime: 'Estimated time',
    arrival: 'arrival by',
    preparation: 'Preparation',
    travel: 'Travel',
    driverPosition: 'Driver position',
    liveTracking: 'Live tracking',
    discussion: 'Discussion',
    channelArchived: 'Channel archived',
    withDriver: 'With driver',
    withMerchant: 'With merchant',
    noMessages: 'No messages yet.',
    discussionEnded: 'Discussion ended.',
    writeMessage: 'Write a message...',
    channelClosed: 'Channel closed',
    confirmReception: 'Confirm reception (PIN code)',
    reportProblem: 'Report a problem',
    disputeSuccess: 'Dispute opened successfully...',
    disputePending: 'A dispute is in progress...',
    history: 'History',
    pinCodeHint: 'Enter the 4-digit PIN code received',
    disputeTitle: 'Report a problem',
    incompleteOrder: 'Incomplete order',
    neverDelivered: 'Never delivered',
    lateDelivery: 'Significant delay',
    badCondition: 'Bad condition',
    other: 'Other',
    disputeReason: 'Reason for dispute',
    problemDescription: 'Problem description',
    confirmPassword: 'Confirm your password',
    send: 'Send',
    sending2: 'Sending...',
    notifOrder: 'Order',
    notifDelivery: 'Delivery',
    notifPromo: 'Promo',
    notifAccount: 'Account',
    notifSystem: 'System',
    notificationsTitle: 'Notifications',
    markAllRead: 'Mark all as read',
    noNotifications: 'No notifications',
    verifyAccount: 'Verify your account',
    codeSentTo: 'A 6-digit code has been sent to',
    verifiedSuccess: 'Account verified!',
    redirecting: 'Redirecting...',
    verifying: 'Verifying...',
    verify: 'Verify',
    resendIn: 'Resend code in...',
    resendCode: 'Resend code',
    backToRegister: 'Back to registration',
    loginTitle: 'Login',
    loginSubtitle: 'Access your FasoFree account',
    emailOrPhone: 'Email or Phone',
    password: 'Password',
    loginButton: 'Log in',
    forgotPassword: 'Forgot password?',
    noAccount: "Don't have an account?",
    createAccount: 'Create an account',
    loginError: 'Incorrect email or password',
    sendLink: 'Send link',
    backToLogin: 'Back to login',
    resetPassword: 'Reset',
    passwordReset: 'Password reset! Redirecting...',
    registerTitle: 'Create an account',
    registerSubtitle: 'Join FasoFree',
    clientTab: 'Customer',
    merchantTab: 'Merchant',
    driverTab: 'Driver',
    yourBusiness: 'Your business',
    yourDriverProfile: 'Your driver profile',
    documents: 'Documents (attachment)',
    referralCode: 'Referral code',
    createClientAccount: 'Create my customer account',
    sendMerchantApp: 'Submit merchant application',
    sendDriverApp: 'Submit driver application',
    alreadyHaveAccount: 'Already have an account?',
    appSent: 'Application submitted!',
    backToHome: 'Back to home',
    orderReceipt: 'Order receipt',
    loadingReceipt: 'Loading receipt...',
    loadReceiptError: 'Unable to load order details.',
    orderConfirmed: 'Order confirmed!',
    orderInProgress: 'Order in progress...',
    paidSuccess: 'Your order was paid successfully',
    waitingConfirmation: 'Your order is awaiting confirmation',
    date: 'Date',
    status: 'Status',
    orderedItems: 'Ordered items',
    totalPaid: 'Total paid',
    download: 'Download',
    trackOrder: 'Track my order',
    thankYou: 'Thank you for your trust!',
    confirmationEmail: 'A confirmation email has been sent to your address.',
    addressesTitle: 'Delivery addresses',
    noAddresses: 'No saved addresses',
    addAddress: 'Add an address',
    defaultLabel: 'Default',
    newAddress: 'New address',
    editAddress: 'Edit address',
    home: 'Home',
    office: 'Office',
    parents: "Parents' place",
    otherAddress: 'Other',
    fullAddressLabel: 'Full address',
    useGps: 'Use my GPS position',
    positionSaved: 'Position saved',
    setDefault: 'Set as default address',
    deleteAddress: 'Delete this address?',
    tagline: 'The city at your table.',
    footerDesc: 'Premium food delivery in Ouagadougou and across Burkina Faso.',
    links: 'Links',
    privacyPolicy: 'Privacy policy',
    terms: 'Terms of service',
    contact: 'Contact',
    allRightsReserved: 'All rights reserved.',
    rideTitle: 'FasoFree Ride',
    economy: 'Economy',
    comfort: 'Comfort',
    premium: 'Premium',
    departure: 'Departure point',
    destination: 'Destination',
    contactPhone: 'Phone',
    vehicleType: 'Vehicle type',
    fareEstimate: 'Fare estimate',
    estimateFare: 'Estimate fare',
    estimating: 'Estimating...',
    confirmRide: 'Confirm ride',
    confirming: 'Confirming...',
    rideConfirmed: 'Ride confirmed!',
    trackRide: 'Track my ride live',
    p2pTitle: 'Send a package',
    p2pDesc: 'On-demand trip - Point A to Point B',
    pickupAddress: 'Pickup address',
    deliveryAddress2: 'Delivery address',
    contactName: 'Contact name',
    recipientName: 'Recipient name',
    contactPhone2: 'Contact phone',
    recipientPhone: 'Recipient phone',
    packageDetails: 'Package details',
    packageDesc: 'Package description',
    weight: 'Estimated weight (kg)',
    declaredValue: 'Declared package value (FCFA)',
    fragile: 'Fragile package',
    fragilityFee: 'Fragility surcharge',
    weightFee: 'Weight surcharge',
    previous: 'Previous',
    continue: 'Continue',
    confirmTrip: 'Confirm trip',
    tripConfirmed: 'Trip confirmed!',
    sendAnother: 'Send another package',
    artOfTable: 'The art of the table',
  },
  mo: {
    home: 'Da',
    search: 'Tõondo',
    cart: 'Gaata',
    orders: 'Wẽndã',
    profile: 'Profil',
    loading: 'Ka tilim...',
    error: 'Ye',
    success: 'Ye',
    yes: 'Aao',
    no: 'Kã',
    save: 'Ka',
    cancel: 'Ka tãa',
    confirm: 'Ka',
    back: 'Bɩr',
    retry: 'Fã fãa',
    close: 'Fã',
    delete: 'Ka yi',
    edit: 'Fãa',
    add: 'Ka tɩŋ',
    deliveryTo: 'Ka dimi',
    searchPlaceholder: 'Tõondo sino ca, sino dɔŋ...',
    allRestaurants: 'Dɔŋ yi kãa',
    sendPackage: 'Ka zuu gatã',
    noResults: 'Dɔŋ kãkã tɩ tẽ ne nɩr',
    resetFilters: 'Fã tɩr fãa',
    login: 'Doneso',
    loginAria: 'Doneso',
    homeAria: 'Bɩr ne da',
    profileAria: 'Profil',
    notificationsAria: 'Bãmbã ye',
    heroTagline: 'Sãa wa ye, wakat wa ye',
    heroDesc: 'Ne dɔŋ tontanã, ka dimi ne wã.',
    heroOrder: 'Wẽnda',
    heroLocation: 'Ka dimi · Bois',
    emptyCart: 'Ne gaata ka pete',
    addItems: 'Ka sãa tɩŋ ne gaata',
    exploreRestaurants: 'Ko dɔŋ yi',
    myCart: 'Ne Gaata',
    clearCart: 'Ka gaata yi',
    summary: 'Tɩr tɩr',
    subtotal: 'Tɩr kãngã',
    deliveryFee: 'Ka dimi fã',
    serviceFee: 'Baara fã',
    estimatedTotal: 'Tɩr yãa',
    calculatedNext: 'Nɩr ne tɩr yãa',
    minimumOrder: 'Wẽndã tɩr',
    placeOrder: 'Wẽnda',
    securePayment: 'Paii ye ne Orange Money, Moov Money nɛ Wave',
    myProfile: 'Ne Profil',
    fullName: 'Rũma wa',
    email: 'Email',
    phone: 'Tɩɩfõ',
    address: 'Yãa',
    notificationChannel: 'Bãmbã tontanã',
    saving: 'Ka tilim...',
    saved: 'Ka ye wa',
    addresses: 'Yãa ka dimi',
    paymentInfo: 'Paii ne',
    notifications: 'Bãmbã ye',
    settings: 'Dirteesga',
    logout: 'Yã',
    myOrders: 'Ne wẽndã',
    myReceipts: 'Ne zan ŋwa',
    favorites: 'Tontanã',
    noOrders: 'Wẽndã kãkã',
    noReceipts: 'Zan ŋwa kãkã',
    noFavorites: 'Tontanã kãkã',
    addFavoritesHint: 'Ka tontanã tɩŋ ne mutuy',
    orderNow: 'Wẽnda',
    articles: 'sãa',
    mobileMoneyNumber: 'Tɩɩfõ Mobile Money',
    operator: 'Baara kã',
    selectOperator: 'Ka baara kã fã',
    paymentInfoDesc: 'Ni ne tɩɩfõ Mobile Money ne ka dimi nɛ ka sãa.',
    vipPass: 'FasoFree Pass VIP',
    activeMember: 'Ye ka baara',
    exclusiveAdvantage: 'Tontanã ye',
    platformFeesFree: 'Baara fã ka ye',
    switchToVip: 'Ka ne FasoFree Pass VIP',
    vipDesc: 'Ni ne wẽndã, baara fã ne {fee} ne wẽndã ka yi. Ka dimi ka nɩr ne tɩr (min. 800 FCFA).',
    feePerOrder: '100 FCFA ka ye ne wẽndã',
    noCommitment: 'Kã ka tɩŋ',
    fasoFreeWallet: 'FasoFree Wallet',
    refresh: 'Ka fã',
    myStatus: 'Ne status',
    activeSub: 'Wẽndã {plan} ka baara',
    expiresOn: 'Ka pe {date}',
    notSubscribed: 'Kã ka wẽnda Pass VIP.',
    chooseOffer: 'Ka ne tontanã fã',
    loadingOffers: 'Ka tilim tontanã...',
    autoRenew: 'Ka fãa ka fã',
    subscribeFor: 'Wẽnda ne {price} FCFA',
    subscribing: 'Ka wẽnda...',
    alreadyVip: 'Ne ka Pass VIP ne wa',
    vipActiveDesc: 'Ne wẽndã kã ka 100 FCFA baara fã.',
    rechargeWallet: 'Ka sãa tɩŋ ne wallet',
    amountFcfa: 'Sãa (FCFA)',
    recharge: 'Ka sãa tɩŋ',
    recharging: 'Ka sãa tɩŋ...',
    myPoints: 'Ne points',
    pointsPerSpent: '1 point / 100 FCFA ne sãa',
    equivalentReduction: 'tɩr: {amount} FCFA ka yi',
    referFriend: 'Ka tontanã tɩŋ',
    friendsRegistered: '{count} tontanã ne wa',
    referred: 'Tontanã',
    pendingPoints: 'Points ka pete',
    referrerBonus: 'Tontanã: +500 pts | Filleul: +200 pts ne 1er achat',
    checkout: 'Wẽnda',
    delivery: 'Ka dimi',
    pickup: 'Ka zuu',
    dineIn: 'Ka sãa ne wa',
    fulfillmentQuestion: 'Ni nɩr ne wẽndã?',
    deliveryAddress: 'Yãa ka dimi',
    fullAddress: 'Yãa kãa',
    deliveryInstructions: 'Yãa ni ka dimi',
    contactInfo: 'Ni tontan ne tɩɩfõ',
    paymentMethod: 'Paii ni',
    sending: 'Ka zuu...',
    confirmOrder: 'Ka wẽndã fã',
    selectPosition: 'Ka ne yãa fã',
    toBeCalculated: 'Nɩr ne tɩr',
    gpsHint: 'Ka "Utiliser ma position actuelle" ni ne tɩr.',
    tableNumber: 'Tabili (tɩ tɩŋ)',
    guests: 'Ni ne wa sãa',
    specialRequest: 'Tontanã tɩ tɩŋ',
    landmark: 'Yãa tɩ tɩŋ',
    useCurrentPosition: 'Ne yãa wa',
    enterAnotherAddress: 'Yãa yãa',
    pickupInfo: 'Ka zuu ne wẽndã ne dɔŋ.',
    onSite: 'Ne wa',
    myOrdersTitle: 'Ne Wẽndã',
    statusPending: 'Ka pete',
    statusPaid: 'Ka ye wa',
    statusPreparing: 'Ka sãa',
    statusReady: 'Ka ye wa',
    statusDriverEnRoute: 'Ka dimi',
    statusDelivered: 'Ka dimi wa',
    statusCompleted: 'Ka ye wa',
    statusCancelled: 'Ka tã wa',
    filterAll: 'Kãa',
    filterPending: 'Ka pete',
    filterPaid: 'Ka ye wa',
    filterDelivered: 'Ka dimi wa',
    filterCancelled: 'Ka tã wa',
    loadingOrders: 'Ka tilim wẽndã...',
    loadError: 'Tɩ tẽ ne ka tilim ne wẽndã',
    noOrdersYet: 'Wẽndã kãkã',
    orderNumber: 'Wẽndã #',
    searchPlaceholderFull: 'Tõondo sino ca, sino dɔŋ...',
    noResultsFor: 'Kãkã tɩ tẽ ne',
    tryAnother: 'Fã fãa tɩ tõndã',
    searchHint: 'Tõondo sino dɔŋ ca sino sãa',
    loadingRestaurant: 'Ka tilim dɔŋ...',
    restaurantNotFound: 'Dɔŋ kãkã tɩ tẽ',
    searchDish: 'Tõondo sino sãa...',
    allCategories: 'Kãa',
    popular: 'Tontanã',
    menu: 'Menu',
    noDishFound: 'Sãa kãkã tɩ tẽ',
    cartLabel: 'Gaata',
    addToCart: 'Ka tɩŋ',
    added: 'Ka tɩŋ wa',
    chooseBranch: 'Ka dɔŋ fã',
    closed: 'Ka fã wa',
    removeFavorite: 'Ka tontanã yi',
    addFavorite: 'Ka tontanã tɩŋ',
    branchesLabel: 'dɔŋ',
    orderTracking: 'Ka tilim wẽndã',
    stepConfirmed: 'Wẽndã ka ye wa',
    stepPreparing: 'Ka sãa',
    stepEnRoute: 'Ka dimi',
    stepDelivered: 'Ka dimi wa',
    estimatedTime: 'Wakat tɩr',
    arrival: 'ka zuu ne',
    preparation: 'Ka sãa',
    travel: 'Ka dimi',
    driverPosition: 'Ka dimi yãa',
    liveTracking: 'Ka tilim live',
    discussion: 'Ne ni',
    channelArchived: 'Ka fã wa',
    withDriver: 'Ni ka dimi',
    withMerchant: 'Ni dɔŋ',
    noMessages: 'Yam kãkã.',
    discussionEnded: 'Ne ni ka ye wa.',
    writeMessage: 'Ka yam tɩŋ...',
    channelClosed: 'Ka fã wa',
    confirmReception: 'Ka ye ne (Code PIN)',
    reportProblem: 'Ka tontanã tɩŋ',
    disputeSuccess: 'Ka tontanã tɩŋ ka ye wa...',
    disputePending: 'Tontanã ka pete...',
    history: 'Bɩr bɩr',
    pinCodeHint: 'Ka Code PIN 4 tɩŋ ne ka zuu',
    disputeTitle: 'Ka tontanã tɩŋ',
    incompleteOrder: 'Wẽndã ka pete',
    neverDelivered: 'Kãkã ka dimi',
    lateDelivery: 'Wakat tɩ',
    badCondition: 'Yãa ka tɩ',
    other: 'Yãa',
    disputeReason: 'Tontanã ni',
    problemDescription: 'Tontanã yam',
    confirmPassword: 'Ka paaswãã ni',
    send: 'Ka zuu',
    sending2: 'Ka zuu...',
    notifOrder: 'Wẽndã',
    notifDelivery: 'Ka dimi',
    notifPromo: 'Yãmbã ye',
    notifAccount: 'Kaunt',
    notifSystem: 'Dirteesga',
    notificationsTitle: 'Bãmbã ye',
    markAllRead: 'Ka yi kãa ye',
    noNotifications: 'Bãmbã kãkã',
    verifyAccount: 'Ka ne kaunt fã',
    codeSentTo: 'Code 6 tɩŋ ne',
    verifiedSuccess: 'Kaunt ka ye wa!',
    redirecting: 'Ka zuu...',
    verifying: 'Ka fã...',
    verify: 'Ka fã',
    resendIn: 'Ka zuu fã code ne...',
    resendCode: 'Ka zuu fã code',
    backToRegister: 'Bɩr ne ka tɩŋ',
    loginTitle: 'Doneso',
    loginSubtitle: 'Ka ne FasoFree kaunt',
    emailOrPhone: 'Email tɩɩfõ',
    password: 'Paaswãã',
    loginButton: 'Doneso',
    forgotPassword: 'Paaswãã ka tẽ?',
    noAccount: 'Kã ka kaunt?',
    createAccount: 'Ka kaunt tɩŋ',
    loginError: 'Email tɩɩfõ ka tẽ',
    sendLink: 'Ka zuu lien',
    backToLogin: 'Bɩr ne doneso',
    resetPassword: 'Ka fã',
    passwordReset: 'Paaswãã ka fã wa! Ka zuu...',
    registerTitle: 'Ka kaunt tɩŋ',
    registerSubtitle: 'Ka FasoFree tɩŋ',
    clientTab: 'Sãa kã',
    merchantTab: 'Dɔŋ kã',
    driverTab: 'Ka dimi kã',
    yourBusiness: 'Ne dɔŋ',
    yourDriverProfile: 'Ne ka dimi profil',
    documents: 'Zan ŋwa',
    referralCode: 'Code tontanã',
    createClientAccount: 'Ka ne kaunt sãa kã tɩŋ',
    sendMerchantApp: 'Ka zuu dɔŋ kã tɩŋ',
    sendDriverApp: 'Ka zuu ka dimi kã tɩŋ',
    alreadyHaveAccount: 'Ne kaunt ne wa?',
    appSent: 'Ka zuu ka ye wa!',
    backToHome: 'Bɩr ne da',
    orderReceipt: 'Zan ŋwa wẽndã',
    loadingReceipt: 'Ka tilim zan ŋwa...',
    loadReceiptError: 'Tɩ tẽ ne ka tilim zan ŋwa.',
    orderConfirmed: 'Wẽndã ka ye wa!',
    orderInProgress: 'Wẽndã ka pete...',
    paidSuccess: 'Ne wẽndã ka ye wa ne paii',
    waitingConfirmation: 'Ne wẽndã ka pete ne ka ye',
    date: 'Zuuni',
    status: 'Status',
    orderedItems: 'Sãa ne wẽndã',
    totalPaid: 'Tɩr ka ye wa',
    download: 'Ka zuu ŋwa',
    trackOrder: 'Ka tilim ne wẽndã',
    thankYou: 'Tã ne ni!',
    confirmationEmail: 'Email ka zuu ne yãa.',
    addressesTitle: 'Yãa ka dimi',
    noAddresses: 'Yãa kãkã ka pete',
    addAddress: 'Ka yãa tɩŋ',
    defaultLabel: 'Yãa wa',
    newAddress: 'Yãa yãa',
    editAddress: 'Ka yãa fãa',
    home: 'Da',
    office: 'Baara yãa',
    parents: 'Da ne ba',
    otherAddress: 'Yãa',
    fullAddressLabel: 'Yãa kãa',
    useGps: 'Ka ne GPS yãa wa',
    positionSaved: 'Yãa ka ye wa',
    setDefault: 'Ka ne yãa wa fã',
    deleteAddress: 'Ka yãa yi?',
    tagline: 'Wẽẽgẽ da ne tã.',
    footerDesc: 'Sãa ka dimi wa Ouagadougou nɛ Burkina Faso.',
    links: 'Lien yi',
    privacyPolicy: 'Senda kae',
    terms: 'Dirteesga',
    contact: 'Tontanã',
    allRightsReserved: 'Yi kãa ka ye wa.',
    rideTitle: 'FasoFree Ride',
    economy: 'Yɩɩga',
    comfort: 'Neemi',
    premium: 'Laafi',
    departure: 'Yãa ne ka zuu',
    destination: 'Yãa ne ka dimi',
    contactPhone: 'Tɩɩfõ',
    vehicleType: 'Ka tɩŋ ka tɩŋ',
    fareEstimate: 'Tɩr ka dimi',
    estimateFare: 'Tɩr ka dimi',
    estimating: 'Ka tɩr...',
    confirmRide: 'Ka zuu fã',
    confirming: 'Ka fã...',
    rideConfirmed: 'Ka zuu ka ye wa!',
    trackRide: 'Ka tilim ne ka zuu live',
    p2pTitle: 'Ka zuu gatã',
    p2pDesc: 'Ka zuu yãa - Yãa A zuu Yãa B',
    pickupAddress: 'Yãa ne ka zuu',
    deliveryAddress2: 'Yãa ne ka dimi',
    contactName: 'Rũma tontanã',
    recipientName: 'Rũma ne ka zuu',
    contactPhone2: 'Tɩɩfõ tontanã',
    recipientPhone: 'Tɩɩfõ ne ka zuu',
    packageDetails: 'Gatã tɩr',
    packageDesc: 'Gatã yam',
    weight: 'Sãa tɩr (kg)',
    declaredValue: 'Gatã sãa (FCFA)',
    fragile: 'Gatã ka tɩ',
    fragilityFee: 'Ka tɩ fã',
    weightFee: 'Sãa fã',
    previous: 'Bɩr',
    continue: 'Ka fãa',
    confirmTrip: 'Ka zuu fã',
    tripConfirmed: 'Ka zuu ka ye wa!',
    sendAnother: 'Ka zuu gatã yãa',
    artOfTable: 'Tã ne tã',
  },
};

const LanguageContext = createContext();

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState(() => {
    return localStorage.getItem('fasofree_lang') || 'fr';
  });

  const setLanguage = useCallback((newLang) => {
    setLang(newLang);
    localStorage.setItem('fasofree_lang', newLang);
  }, []);

  const t = useCallback((key, params = {}) => {
    let value = translations[lang]?.[key] || translations.fr[key] || key;
    Object.entries(params).forEach(([k, v]) => {
      value = value.replace(new RegExp(`\\{${k}\\}`, 'g'), v);
    });
    return value;
  }, [lang]);

  return (
    <LanguageContext.Provider value={{ lang, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export const useLanguage = () => useContext(LanguageContext);
