import React, { createContext, useContext, useState, useCallback } from 'react';

const translations = {
  fr: {
    // Settings
    settings: 'Paramètres',
    darkMode: 'Mode sombre',
    darkModeOn: 'Actif',
    darkModeOff: 'Inactif — Mode clair',
    privacy: 'Confidentialité',
    privacyDesc: 'Gérez vos données personnelles',
    privacyProfile: 'Qui peut voir mon profil',
    privacyProfileDesc: 'Visible par les partenaires uniquement',
    downloadData: 'Télécharger mes données',
    downloadDataDesc: 'Récupérez une copie de vos informations',
    deleteAccount: 'Supprimer mon compte',
    deleteAccountDesc: 'Action irréversible',
    language: 'Langue',
    notifications: 'Notifications',
    notificationsDesc: 'Gérez vos alertes',
    notifOrders: 'Commandes',
    notifOrdersDesc: 'Statut de vos commandes',
    notifPromos: 'Promotions',
    notifPromosDesc: 'Offres et bons plans',
    notifNewRestaurants: 'Nouveaux restaurants',
    notifNewRestaurantsDesc: 'Quand un partenaire rejoint FasoFree',
    security: 'Sécurité',
    securityDesc: 'Mot de passe et sécurité du compte',
    changePassword: 'Changer le mot de passe',
    about: 'À propos',
    version: 'Version 1.0.0',
    aboutDesc: 'FasoFree — Livraison rapide au Burkina Faso',
    terms: 'Conditions générales',
    privacyPolicy: 'Politique de confidentialité',
    logout: 'Se déconnecter',
    currentPassword: 'Mot de passe actuel',
    newPassword: 'Nouveau mot de passe',
    confirmPassword: 'Confirmer le mot de passe',
    save: 'Enregistrer',
    cancel: 'Annuler',
    confirm: 'Confirmer',
    // Password
    passwordChanged: 'Mot de passe changé avec succès',
    passwordError: 'Erreur lors du changement de mot de passe',
    passwordMismatch: 'Les mots de passe ne correspondent pas',
    passwordTooShort: 'Le mot de passe doit faire au moins 6 caractères',
    // Delete
    deleteConfirmTitle: 'Supprimer votre compte ?',
    deleteConfirmDesc: 'Cette action est irréversible. Toutes vos données seront supprimées.',
    deleteSuccess: 'Votre compte a été supprimé avec succès',
    deleteError: 'Erreur lors de la suppression du compte',
    // Download
    downloadSuccess: 'Vos données ont été téléchargées',
    downloadError: 'Erreur lors du téléchargement',
    // Profile
    myProfile: 'Mon Profil',
    edit: 'Modifier',
    fullName: 'Nom complet',
    email: 'Email',
    phone: 'Téléphone',
    saveProfile: 'Enregistrer',
    profileUpdated: 'Profil mis à jour',
    // Orders
    myOrders: 'Mes commandes',
    orderHistory: 'Historique',
    // Navigation
    home: 'Accueil',
    search: 'Rechercher',
    cart: 'Panier',
    orders: 'Commandes',
    profile: 'Profil',
    // General
    loading: 'Chargement...',
    error: 'Erreur',
    success: 'Succès',
    yes: 'Oui',
    no: 'Non',
  },
  en: {
    settings: 'Settings',
    darkMode: 'Dark mode',
    darkModeOn: 'Active',
    darkModeOff: 'Inactive — Light mode',
    privacy: 'Privacy',
    privacyDesc: 'Manage your personal data',
    privacyProfile: 'Who can see my profile',
    privacyProfileDesc: 'Visible to partners only',
    downloadData: 'Download my data',
    downloadDataDesc: 'Get a copy of your information',
    deleteAccount: 'Delete my account',
    deleteAccountDesc: 'Irreversible action',
    language: 'Language',
    notifications: 'Notifications',
    notificationsDesc: 'Manage your alerts',
    notifOrders: 'Orders',
    notifOrdersDesc: 'Your order status',
    notifPromos: 'Promotions',
    notifPromosDesc: 'Offers and deals',
    notifNewRestaurants: 'New restaurants',
    notifNewRestaurantsDesc: 'When a partner joins FasoFree',
    security: 'Security',
    securityDesc: 'Password and account security',
    changePassword: 'Change password',
    about: 'About',
    version: 'Version 1.0.0',
    aboutDesc: 'FasoFree — Fast delivery in Burkina Faso',
    terms: 'Terms of service',
    privacyPolicy: 'Privacy policy',
    logout: 'Log out',
    currentPassword: 'Current password',
    newPassword: 'New password',
    confirmPassword: 'Confirm password',
    save: 'Save',
    cancel: 'Cancel',
    confirm: 'Confirm',
    passwordChanged: 'Password changed successfully',
    passwordError: 'Error changing password',
    passwordMismatch: 'Passwords do not match',
    passwordTooShort: 'Password must be at least 6 characters',
    deleteConfirmTitle: 'Delete your account?',
    deleteConfirmDesc: 'This action is irreversible. All your data will be deleted.',
    deleteSuccess: 'Your account has been deleted successfully',
    deleteError: 'Error deleting account',
    downloadSuccess: 'Your data has been downloaded',
    downloadError: 'Error downloading data',
    myProfile: 'My Profile',
    edit: 'Edit',
    fullName: 'Full name',
    email: 'Email',
    phone: 'Phone',
    saveProfile: 'Save',
    profileUpdated: 'Profile updated',
    myOrders: 'My orders',
    orderHistory: 'History',
    home: 'Home',
    search: 'Search',
    cart: 'Cart',
    orders: 'Orders',
    profile: 'Profile',
    loading: 'Loading...',
    error: 'Error',
    success: 'Success',
    yes: 'Yes',
    no: 'No',
  },
  mo: {
    settings: 'Dirteesga',
    darkMode: 'Suma',
    darkModeOn: 'Ye',
    darkModeOff: 'Ka tã — Samba',
    privacy: 'Senda kae',
    privacyDesc: 'Ni tontansi ne da wa da',
    privacyProfile: 'A wa tontan ne profil',
    privacyProfileDesc: 'Ni baara nɛ sɛbaa',
    downloadData: 'Ka ne zan ŋwa',
    downloadDataDesc: 'Ni ne baara nɛ fã',
    deleteAccount: 'Ka ne kaunt ni yi',
    deleteAccountDesc: 'Ni yi ka tã',
    language: 'Tɩɩndi',
    notifications: 'Bãmbã ye',
    notificationsDesc: 'Ni tontansi ne bãmbã',
    notifOrders: 'Wẽndã',
    notifOrdersDesc: 'Ni ne wẽndã',
    notifPromos: 'Yãmbã ye',
    notifPromosDesc: 'Yãmbã nɛ sãa',
    notifNewRestaurants: 'Dɔŋ yãa',
    notifNewRestaurantsDesc: 'FasoFree kae dɔŋ yãa',
    security: 'Sendaka',
    securityDesc: 'Ni ne paaswãã',
    changePassword: 'Ka ne paaswãã fã',
    about: 'Bare bare',
    version: 'Version 1.0.0',
    aboutDesc: 'FasoFree — Sãa wa dimi Burkina Faso',
    terms: 'Dirteesga',
    privacyPolicy: 'Senda kae',
    logout: 'Yã',
    currentPassword: 'Ne paaswãã wa',
    newPassword: 'Paaswãã yãa',
    confirmPassword: 'Ka paaswãã yãa ni',
    save: 'Ka',
    cancel: 'Ka tãa',
    confirm: 'Ka',
    passwordChanged: 'Paaswãã ka fã wa',
    passwordError: 'Paaswãã ka fã ka ye',
    passwordMismatch: 'Paaswãã nɛ ka yẽ',
    passwordTooShort: 'Paaswãã ka baibiti 6',
    deleteConfirmTitle: 'Ka ne kaunt ni yi?',
    deleteConfirmDesc: 'Ni yi ka tã. Ne baara yi ka yi.',
    deleteSuccess: 'Ne kaunt ka yi wa',
    deleteError: 'Ne kaunt ka yi ka ye',
    downloadSuccess: 'Ne zan ŋwa ka ye',
    downloadError: 'Ne zan ŋwa ka ye ka ye',
    myProfile: 'Ne profil',
    edit: 'Fãa',
    fullName: 'Rũma wa',
    email: 'Email',
    phone: 'Tɩɩfõ',
    saveProfile: 'Ka',
    profileUpdated: 'Profil ka ye wa',
    myOrders: 'Ne wẽndã',
    orderHistory: 'Bɩr bɩr',
    home: 'Da',
    search: 'Tõondo',
    cart: 'Gaata',
    orders: 'Wẽndã',
    profile: 'Profil',
    loading: 'Ka tilim...',
    error: 'Ye',
    success: 'Ye',
    yes: 'Aao',
    no: 'Kã',
  },
};

const LanguageContext = createContext();

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState(() => {
    return localStorage.getItem('fasofree_lang') || 'fr';
  });

  const setLanguage = useCallback((newLang) => {
    setLang(newLang);
    localStorage.setItem('fasofree_lang', newLang);
  }, []);

  const t = useCallback((key) => {
    return translations[lang]?.[key] || translations.fr[key] || key;
  }, [lang]);

  return (
    <LanguageContext.Provider value={{ lang, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export const useLanguage = () => useContext(LanguageContext);
